### ISSUE TITLE
Sección "Blog - Codigo Banana"

### ISSUE THREAD

**Issue by marsonauta** [platanus/la-guia#100]
Hola!
Entiendo que el siguiente contenido del último punto,

> "Muy cargado hacia el primer punto y tu post será considerado poco académico. Demasiado cargado al segundo punto y será descartado por aburrido"

...es un párrafo independiente del listado. Debiese estar fuera del punto al cual también se refiere.

En otras palabras, entiendo que la idea es la siguiente:

>- El título hace pensar al lector que **ganará algo importante** al leer el post.
>- El títlo es **realista** en cuanto a lo que logrará el lector al leer el post.

>Muy cargado hacia el primer punto y tu post será considerado poco académico. Demasiado cargado al segundo punto y será descartado por aburrido.

Sólo eso. Saludos con TOC. ✌🏻

**Comment by bunzli** [comment]
Gracias @marsonauta. Ya está actualizado el arreglo con el PR #101 .

Saludos
