### ISSUE TITLE
React native

### ISSUE THREAD

**Issue by ldlsegovia** [platanus/la-guia#132]
1. Título
   Descripción corta
2. Por qué lo usamos?
3. Cómo lo usamos? con ejemplo mínimo de uso real. Diciendo con qué versión de la herramienta se hizo el ejemplo.
4. Recursos útiles (links)
5. Sub secciones opcionales. Tips, casos típicos, etc. Lo que sea necesario tratando de que no sea fácilmente deprecated.

**Comment by difernandez** [comment]
Para esto @DiegoAndai empezó a usar [una estructura](https://github.com/platanus/duit-mobile/pull/21/commits/694602704f6a5f3c48848dcbe0d02f729dbc43c4) que se ve bien buena, se podría mencionar en esta sección de la guía y que lo tengamos como estándar, o base para uno
