### ISSUE TITLE
Setup > Local > Tecnologías > Docker > Linux

### ISSUE THREAD

**Issue by iaacosta** [platanus/la-guia#201]
- Cómo instalar (`apt` o `source`)
- Tips y errores comunes

**Comment by jgmontoya** [comment]
O recién caché que @flouMicaza se había asignado esta!

Alcancé a escribir esto:


Desinstalar posibles versiones antiguas

```bash
 sudo apt-get remove docker docker-engine docker.io containerd runc
```

Nota: no hay problema si apt reporta que ninguna de esos paquetes estaba instalado.

Instala algunas dependencias:
```bash
sudo apt update
```
```bash
sudo apt-get install \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg \
    lsb-release
```

Agrega la llave GPG oficial de docker

```bash
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
```

Con el siguiente comando configuramos el repositorio:

```bash
echo \
  "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
  $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
```

Nota: Este comando es específico a arquitecturas x86_64 / amd64. Para otras arquitecturas (como armhf o arm64 puedes buscar el comando acá: https://docs.docker.com/engine/install/ubuntu/)

```bash
sudo apt-get update

sudo apt-get install docker-ce docker-ce-cli containerd.io
```

Con esto ya estará instalado docker, sin embargo debemos hacer lo siguiente para poder usarlo sin sudo:

Crea un grupo unix llamado `docker` y agrega tu usuario a este

```bash
sudo groupadd docker
```
```bash
sudo usermod -aG docker $USER
```

Corre el siguiente comando para activar los cambios:
```bash
newgrp docker
```
Ahora ya deberíamos poder correr docker sin sudo, puedes verificarlo haciendo `docker run hello-world`. Si no funciona intenta reiniciando tu computador.

**Comment by flouMicaza** [comment]
jjajajaj habría avanzado mas o menos lo mismo. Voy a juntar las dos versiones (:
