### ISSUE TITLE
rubocop 0.47 doesn't work with current .rubocop.yml

### ISSUE THREAD

**Issue by llekn** [platanus/la-guia#56]
Installing last version of rubocop (0.47) doesn't check any files and throws the following errors:
```
/home/camilo/workspace/platanus/.rubocop.yml: Lint/Eval has the wrong namespace - should be Security
Error: The `Style/MethodCallParentheses` cop has been renamed to `Style/MethodCallWithoutArgsParentheses`.
(obsolete configuration found in /home/camilo/workspace/platanus/.rubocop.yml, please update it)
obsolete parameter IndentWhenRelativeTo (for Style/CaseIndentation) found in /home/camilo/workspace/platanus/.rubocop.yml
`IndentWhenRelativeTo` has been renamed to `EnforcedStyle`
obsolete parameter AlignWith (for Lint/EndAlignment) found in /home/camilo/workspace/platanus/.rubocop.yml
`AlignWith` has been renamed to `EnforcedStyleAlignWith`
obsolete parameter AlignWith (for Lint/DefEndAlignment) found in /home/camilo/workspace/platanus/.rubocop.yml
`AlignWith` has been renamed to `EnforcedStyleAlignWith`
```
Steps to reproduce the problem:

1. Install rubocop version 0.47: `gem install rubocop -v 0.47`
2. Run `rubocop` on any project

**Comment by ldlsegovia** [comment]
@llekn la version de rubocop que estamos usando según "tradición oral" es la 0.46.
https://github.com/platanus/potassium/blob/master/lib/potassium/version.rb

**Comment by llekn** [comment]
Así me di cuenta... Estuve buscando esa especificación de versión en la guía pero no la encontré!

Con 0.46 funciona :ok_hand: , de todas maneras levanté el Issue para que lo tengamos presente y quizás algún día arreglarlo

**Comment by ldlsegovia** [comment]
Sí, perfect

**Comment by ldlsegovia** [comment]
ups, cerré jaa

**Comment by llekn** [comment]
Closed by #60 and #61
