### ISSUE TITLE
Merge trello sections

### ISSUE THREAD

**Issue by blackjid** [platanus/la-guia#66]
I think there two sections that talk about trello and how we use it. It would be nice to simplify that.

**Comment by ldlsegovia** [comment]
Se borraron las secciones y sólo se menciona trello como herramienta usada. https://github.com/platanus/la-guia/blob/master/tools/comunicacion/README.md
La forma interna de trabajar, que no es de mucha utilidad para visitantes de github, la vamos a dejar en el notion.
